site_name: Meatballs - recipes from CG Team
repo_url: https://github.com/clinical-genomics/meatballs/
site_author: Clinical Genomics bioinfo team
dev_addr: 0.0.0.0:8080

extra:
  version: 0.6.33

markdown_extensions:
    - mdtooltips
    - markdown_include.include:
          base_path: docs
    - pymdownx.superfences

theme:
    name: "material"
    logo: "img/meatballs.png"
    palette:
        primary: "orange"
        accent: "amber"

extra_css:
    - css/tooltips.css

nav:
  - Home: 'index.md'
  - Cocktails:
      - Charlie Chaplin: "cocktails/CharlieChaplin.md"
      - Old fashioned: "cocktails/Oldfashioned.md"
      - Zombie: "cocktails/Zombie.md"
  - Non alcoholic drinks:
       - Sunshine: "non_alcoholic_drinks/sunshine.md"    
  - Pastas & similar:
      - Gnocchi with Pumpkin: "main-courses/pastas/gnocchi_with_pumpkin.md"
      - Lasagne: "main-courses/pastas/lasagne.md"
      - Spaghetti Carbonara: "main-courses/pastas/carbonara.md"
  - Sauces/Curry:
      - Indian Dal recipe: "main-courses/Currys/dalrecipe.md" 
      - Risotto: "dinner/risotto.md"
  - Main courses:
      - Tortilla: "main-courses/tortilla.md" 
      - Congee: "main-courses/congee.md"
      - Pitepalt: "main-courses/pitepalt.md"
      - Broccoli- och ärtsoppa: "main-courses/BroccoliSoppa.md"
      - Water Soup: "main-courses/water_soup.md"
  - Breakfast:
      - Porridge: "breakfast/porridge.md" 
      - Boiled Eggs: "breakfast/boiled_egg.md"   
      - American pancakes: "breakfast/pancakes.md"
      - Fluffy american pancakes: "breakfast/american_pancakes.md"
  - Desserts:
      - Desserts: "Desserts/fruit_sallad.md"
      - Cheesecake: "Desserts/cheesecake.md"
      - Ice cream: "Desserts/ice_cream.md"
  - Fika:
      - Sockerkaka: "fika/sockerkaka.md"
      - Pumpakaka: "fika/pumpakaka.md"
      - Chokladbollar: "fika/Chokladbollar.md"
      - Kladdkaka: "fika/kladdkaka.md" 
      - Kladdkakemuffins: "fika/Kladdkakemuffins.md" 
      - Kanelbullar: "fika/Kanelbullar.md"
      - Pear and lingonberry cake: "fika/pear_cake.md"
      - Smulpaj med äpple: "fika/smulpaj_with_apple.md"
      - Cardemon cake with lemon: "fika/Cardemon_cake_with_lemon.md"
      - Gingercookies with molasses: "fika/gingercookies.md"
      - Hjortron macarons: "fika/hjortron_macarons.md"
  - Lunch:
      - Greek salad: "lunch/Salad.md"
      - Meatballs: "lunch/Meatballs.md"
      - Sweet Potato Quesadillas: "lunch/Sweet_potato_quesadilla.md"
  - Snacks:
      - Popcorn: "snacks/popcorn.md"
      - Chips: "snacks/potato_chips.md"
      - Nuts: "snacks/nuts.md"
